# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from odom_pub/motor_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motor_msg(genpy.Message):
  _md5sum = "0e4c0fdbf8c8204c136aa0e02d2bf289"
  _type = "odom_pub/motor_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 driver_motor_01     
float64 driver_motor_02
float64 driver_motor_03
float64 driver_motor_04

float64 steer_motor_01
float64 steer_motor_02
float64 steer_motor_03
float64 steer_motor_04

"""
  __slots__ = ['driver_motor_01','driver_motor_02','driver_motor_03','driver_motor_04','steer_motor_01','steer_motor_02','steer_motor_03','steer_motor_04']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       driver_motor_01,driver_motor_02,driver_motor_03,driver_motor_04,steer_motor_01,steer_motor_02,steer_motor_03,steer_motor_04

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motor_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.driver_motor_01 is None:
        self.driver_motor_01 = 0.
      if self.driver_motor_02 is None:
        self.driver_motor_02 = 0.
      if self.driver_motor_03 is None:
        self.driver_motor_03 = 0.
      if self.driver_motor_04 is None:
        self.driver_motor_04 = 0.
      if self.steer_motor_01 is None:
        self.steer_motor_01 = 0.
      if self.steer_motor_02 is None:
        self.steer_motor_02 = 0.
      if self.steer_motor_03 is None:
        self.steer_motor_03 = 0.
      if self.steer_motor_04 is None:
        self.steer_motor_04 = 0.
    else:
      self.driver_motor_01 = 0.
      self.driver_motor_02 = 0.
      self.driver_motor_03 = 0.
      self.driver_motor_04 = 0.
      self.steer_motor_01 = 0.
      self.steer_motor_02 = 0.
      self.steer_motor_03 = 0.
      self.steer_motor_04 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.driver_motor_01, _x.driver_motor_02, _x.driver_motor_03, _x.driver_motor_04, _x.steer_motor_01, _x.steer_motor_02, _x.steer_motor_03, _x.steer_motor_04))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.driver_motor_01, _x.driver_motor_02, _x.driver_motor_03, _x.driver_motor_04, _x.steer_motor_01, _x.steer_motor_02, _x.steer_motor_03, _x.steer_motor_04,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.driver_motor_01, _x.driver_motor_02, _x.driver_motor_03, _x.driver_motor_04, _x.steer_motor_01, _x.steer_motor_02, _x.steer_motor_03, _x.steer_motor_04))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.driver_motor_01, _x.driver_motor_02, _x.driver_motor_03, _x.driver_motor_04, _x.steer_motor_01, _x.steer_motor_02, _x.steer_motor_03, _x.steer_motor_04,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
