// Generated by gencpp from file ur3_move/getObjectPosition.msg
// DO NOT EDIT!


#ifndef UR3_MOVE_MESSAGE_GETOBJECTPOSITION_H
#define UR3_MOVE_MESSAGE_GETOBJECTPOSITION_H

#include <ros/service_traits.h>


#include <ur3_move/getObjectPositionRequest.h>
#include <ur3_move/getObjectPositionResponse.h>


namespace ur3_move
{

struct getObjectPosition
{

typedef getObjectPositionRequest Request;
typedef getObjectPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getObjectPosition
} // namespace ur3_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur3_move::getObjectPosition > {
  static const char* value()
  {
    return "914a1e14d98b3c79e57093c7bd6ee205";
  }

  static const char* value(const ::ur3_move::getObjectPosition&) { return value(); }
};

template<>
struct DataType< ::ur3_move::getObjectPosition > {
  static const char* value()
  {
    return "ur3_move/getObjectPosition";
  }

  static const char* value(const ::ur3_move::getObjectPosition&) { return value(); }
};


// service_traits::MD5Sum< ::ur3_move::getObjectPositionRequest> should match
// service_traits::MD5Sum< ::ur3_move::getObjectPosition >
template<>
struct MD5Sum< ::ur3_move::getObjectPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur3_move::getObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::getObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur3_move::getObjectPositionRequest> should match
// service_traits::DataType< ::ur3_move::getObjectPosition >
template<>
struct DataType< ::ur3_move::getObjectPositionRequest>
{
  static const char* value()
  {
    return DataType< ::ur3_move::getObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::getObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur3_move::getObjectPositionResponse> should match
// service_traits::MD5Sum< ::ur3_move::getObjectPosition >
template<>
struct MD5Sum< ::ur3_move::getObjectPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur3_move::getObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::getObjectPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur3_move::getObjectPositionResponse> should match
// service_traits::DataType< ::ur3_move::getObjectPosition >
template<>
struct DataType< ::ur3_move::getObjectPositionResponse>
{
  static const char* value()
  {
    return DataType< ::ur3_move::getObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::getObjectPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR3_MOVE_MESSAGE_GETOBJECTPOSITION_H
