// Generated by gencpp from file ur3_move/movingObjectPosition.msg
// DO NOT EDIT!
/*这个头文件定义了一个ROS service消息类型 movingObjectPosition，包含了请求(Request)和响应(Response)两个部分。
这个消息类型的具体定义在 ur3_move/movingObjectPosition.msg 文件中生成，并被包含在这个头文件中。

该头文件还包含了ROS中与服务相关的一些特殊定义和数据类型，例如MD5校验和和数据类型，
这些定义和数据类型用于确保消息在ROS系统中的一致性和正确性。这些定义和数据类型由ROS系统自动生成，
并被包含在ROS服务消息的头文件中。*/

#ifndef UR3_MOVE_MESSAGE_MOVINGOBJECTPOSITION_H
#define UR3_MOVE_MESSAGE_MOVINGOBJECTPOSITION_H

#include <ros/service_traits.h>


#include <ur3_move/movingObjectPositionRequest.h>
#include <ur3_move/movingObjectPositionResponse.h>


namespace ur3_move
{

struct movingObjectPosition
{

typedef movingObjectPositionRequest Request;
typedef movingObjectPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct movingObjectPosition
} // namespace ur3_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur3_move::movingObjectPosition > {
  static const char* value()
  {
    return "05475c87257688fa5ef65958faf092d7";
  }

  static const char* value(const ::ur3_move::movingObjectPosition&) { return value(); }
};

template<>
struct DataType< ::ur3_move::movingObjectPosition > {
  static const char* value()
  {
    return "ur3_move/movingObjectPosition";
  }

  static const char* value(const ::ur3_move::movingObjectPosition&) { return value(); }
};


// service_traits::MD5Sum< ::ur3_move::movingObjectPositionRequest> should match
// service_traits::MD5Sum< ::ur3_move::movingObjectPosition >
template<>
struct MD5Sum< ::ur3_move::movingObjectPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur3_move::movingObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::movingObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur3_move::movingObjectPositionRequest> should match
// service_traits::DataType< ::ur3_move::movingObjectPosition >
template<>
struct DataType< ::ur3_move::movingObjectPositionRequest>
{
  static const char* value()
  {
    return DataType< ::ur3_move::movingObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::movingObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur3_move::movingObjectPositionResponse> should match
// service_traits::MD5Sum< ::ur3_move::movingObjectPosition >
template<>
struct MD5Sum< ::ur3_move::movingObjectPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur3_move::movingObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::movingObjectPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur3_move::movingObjectPositionResponse> should match
// service_traits::DataType< ::ur3_move::movingObjectPosition >
template<>
struct DataType< ::ur3_move::movingObjectPositionResponse>
{
  static const char* value()
  {
    return DataType< ::ur3_move::movingObjectPosition >::value();
  }
  static const char* value(const ::ur3_move::movingObjectPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR3_MOVE_MESSAGE_MOVINGOBJECTPOSITION_H
