// Generated by gencpp from file ur3_move/varObjectsPosition.msg
// DO NOT EDIT!


#ifndef UR3_MOVE_MESSAGE_VAROBJECTSPOSITION_H
#define UR3_MOVE_MESSAGE_VAROBJECTSPOSITION_H

#include <ros/service_traits.h>


#include <ur3_move/varObjectsPositionRequest.h>
#include <ur3_move/varObjectsPositionResponse.h>


namespace ur3_move
{

struct varObjectsPosition
{

typedef varObjectsPositionRequest Request;
typedef varObjectsPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct varObjectsPosition
} // namespace ur3_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur3_move::varObjectsPosition > {
  static const char* value()
  {
    return "471fff188bc2b994ff747dcd01944fb6";
  }

  static const char* value(const ::ur3_move::varObjectsPosition&) { return value(); }
};

template<>
struct DataType< ::ur3_move::varObjectsPosition > {
  static const char* value()
  {
    return "ur3_move/varObjectsPosition";
  }

  static const char* value(const ::ur3_move::varObjectsPosition&) { return value(); }
};


// service_traits::MD5Sum< ::ur3_move::varObjectsPositionRequest> should match
// service_traits::MD5Sum< ::ur3_move::varObjectsPosition >
template<>
struct MD5Sum< ::ur3_move::varObjectsPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur3_move::varObjectsPosition >::value();
  }
  static const char* value(const ::ur3_move::varObjectsPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur3_move::varObjectsPositionRequest> should match
// service_traits::DataType< ::ur3_move::varObjectsPosition >
template<>
struct DataType< ::ur3_move::varObjectsPositionRequest>
{
  static const char* value()
  {
    return DataType< ::ur3_move::varObjectsPosition >::value();
  }
  static const char* value(const ::ur3_move::varObjectsPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur3_move::varObjectsPositionResponse> should match
// service_traits::MD5Sum< ::ur3_move::varObjectsPosition >
template<>
struct MD5Sum< ::ur3_move::varObjectsPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur3_move::varObjectsPosition >::value();
  }
  static const char* value(const ::ur3_move::varObjectsPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur3_move::varObjectsPositionResponse> should match
// service_traits::DataType< ::ur3_move::varObjectsPosition >
template<>
struct DataType< ::ur3_move::varObjectsPositionResponse>
{
  static const char* value()
  {
    return DataType< ::ur3_move::varObjectsPosition >::value();
  }
  static const char* value(const ::ur3_move::varObjectsPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR3_MOVE_MESSAGE_VAROBJECTSPOSITION_H
