// Generated by gencpp from file gohome/carArmRequest.msg
// DO NOT EDIT!


#ifndef GOHOME_MESSAGE_CARARMREQUEST_H
#define GOHOME_MESSAGE_CARARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gohome
{
template <class ContainerAllocator>
struct carArmRequest_
{
  typedef carArmRequest_<ContainerAllocator> Type;

  carArmRequest_()
    : location()  {
    }
  carArmRequest_(const ContainerAllocator& _alloc)
    : location(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::gohome::carArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gohome::carArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct carArmRequest_

typedef ::gohome::carArmRequest_<std::allocator<void> > carArmRequest;

typedef boost::shared_ptr< ::gohome::carArmRequest > carArmRequestPtr;
typedef boost::shared_ptr< ::gohome::carArmRequest const> carArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gohome::carArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gohome::carArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gohome::carArmRequest_<ContainerAllocator1> & lhs, const ::gohome::carArmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gohome::carArmRequest_<ContainerAllocator1> & lhs, const ::gohome::carArmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gohome

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gohome::carArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gohome::carArmRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gohome::carArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gohome::carArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gohome::carArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gohome::carArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gohome::carArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03da474bc61cfeb81a8854b4ca05bafa";
  }

  static const char* value(const ::gohome::carArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03da474bc61cfeb8ULL;
  static const uint64_t static_value2 = 0x1a8854b4ca05bafaULL;
};

template<class ContainerAllocator>
struct DataType< ::gohome::carArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gohome/carArmRequest";
  }

  static const char* value(const ::gohome::carArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gohome::carArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string location\n"
;
  }

  static const char* value(const ::gohome::carArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gohome::carArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct carArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gohome::carArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gohome::carArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOHOME_MESSAGE_CARARMREQUEST_H
