// Generated by gencpp from file lslidar_n301_msgs/LslidarN301Difop.msg
// DO NOT EDIT!


#ifndef LSLIDAR_N301_MSGS_MESSAGE_LSLIDARN301DIFOP_H
#define LSLIDAR_N301_MSGS_MESSAGE_LSLIDARN301DIFOP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_n301_msgs
{
template <class ContainerAllocator>
struct LslidarN301Difop_
{
  typedef LslidarN301Difop_<ContainerAllocator> Type;

  LslidarN301Difop_()
    : temperature(0)
    , rpm(0)  {
    }
  LslidarN301Difop_(const ContainerAllocator& _alloc)
    : temperature(0)
    , rpm(0)  {
  (void)_alloc;
    }



   typedef int64_t _temperature_type;
  _temperature_type temperature;

   typedef int64_t _rpm_type;
  _rpm_type rpm;





  typedef boost::shared_ptr< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> const> ConstPtr;

}; // struct LslidarN301Difop_

typedef ::lslidar_n301_msgs::LslidarN301Difop_<std::allocator<void> > LslidarN301Difop;

typedef boost::shared_ptr< ::lslidar_n301_msgs::LslidarN301Difop > LslidarN301DifopPtr;
typedef boost::shared_ptr< ::lslidar_n301_msgs::LslidarN301Difop const> LslidarN301DifopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator1> & lhs, const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator2> & rhs)
{
  return lhs.temperature == rhs.temperature &&
    lhs.rpm == rhs.rpm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator1> & lhs, const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_n301_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9ba6a08f315575f30cfd23b074c07a8";
  }

  static const char* value(const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9ba6a08f315575fULL;
  static const uint64_t static_value2 = 0x30cfd23b074c07a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_n301_msgs/LslidarN301Difop";
  }

  static const char* value(const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 temperature\n"
"int64 rpm\n"
;
  }

  static const char* value(const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
      stream.next(m.rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LslidarN301Difop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_n301_msgs::LslidarN301Difop_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    Printer<int64_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "rpm: ";
    Printer<int64_t>::stream(s, indent + "  ", v.rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_N301_MSGS_MESSAGE_LSLIDARN301DIFOP_H
